import {execSync} from "child_process";
import * as fs from 'fs';
import path from 'path';

const PACKAGE_NAME = process.env.npm_package_name;
const PACKAGE_VERSION = process.env.npm_package_version;
// from https://gist.github.com/wosephjeber/212f0ca7fea740c3a8b03fc2283678d3
const GIT_BRANCH = process.env.GIT_LOCAL_BRANCH || execSync("git rev-parse --abbrev-ref HEAD").toString("utf8").replace(/[\n\r\s]+$/, "");
const GIT_COMMIT = process.env.npm_package_gitHead || execSync("git rev-parse HEAD").toString("utf8").replace(/[\n\r\s]+$/, "");

fs.writeFileSync(path.resolve(process.cwd(), "./src/version.ts"),
	`// This file is auto-generated by the build system.
export const PACKAGE_NAME: string = "${PACKAGE_NAME}";
export const PACKAGE_VERSION: string = "${PACKAGE_VERSION}";
export const GIT_BRANCH: string | undefined = "${GIT_BRANCH}";
export const GIT_COMMIT: string | undefined = "${GIT_COMMIT}";
`);
