
// This file is auto-generated by dill-pixel. Do not edit.
import type { dataSchema, actions, contexts } from '../../dill-pixel.config';
import type { V8Application } from '../V8Application';
// Data
type AppData = typeof dataSchema;

// Action Contexts
type AppContexts = (typeof contexts)[number];

// Actions
type AppActionMap = typeof actions;
type AppActions = keyof AppActionMap;

// Scenes
type AppScenes = 
  | 'base'
  | 'focus'
  | 'voiceover'
  | 'audio'
  | 'music'
  | 'animated-sprites'
  | 'spine'
  | 'assets'
  | 'pause'
  | 'timer'
  | 'endless-runner'
  | 'crunch-physics'
  | 'matter-physics'
  | 'matter-platformer'
  | 'snap-collisions'
  | 'snap-endless-runner'
  | 'snap-physics'
  | 'snap-projectiles'
  | 'rive'
  | 'firebase-adapter'
  | 'buttons'
  | 'flex-container'
  | 'ui-popup'
  | 'text'
  | 'ui-canvas'
  | 'ui-input'
  | 'ui-toaster';

// Plugins
type AppPlugins = 
  | 'crunch-physics'
  | 'google-analytics'
  | 'matter-physics'
  | 'rive'
  | 'rollbar'
  | 'snap-physics'
  | 'springroll'
  | 'test';

// Storage adapters
type AppStorageAdapters = 
  | 'firebase'
  | 'supabase';

/**
 * Add type overrides to the framework
 */
declare module 'dill-pixel' {
  interface AppTypeOverrides {
    App: V8Application;
    Data: AppData;
    Contexts: AppContexts;
    Actions: AppActions;
    ActionMap: AppActionMap;
    Scenes: AppScenes;
    Plugins: AppPlugins;
    StorageAdapters: AppStorageAdapters;
    Eases: Eases;
  }
}
