import { sayHello } from './hello';
export * from './core';
export * from './audio';
export * from './copy';
export * from './gameobjects';
export * from './ui';
export * from './input';
export { KeyCodes } from './input';
export * from './load';
export * from './physics';
export * from './popup';
export * from './save';
export * from './state';
export * from './utils';
export * from './signals';
export * from './functions';
export { Add, Make } from './utils/factory';
export * from './pixi';
sayHello();
//# sourceMappingURL=index.js.map