// This file is auto-generated by the build system.
export const PACKAGE_NAME = "html-living-framework";
export const PACKAGE_VERSION = "1.6.1";
export const GIT_BRANCH = "main";
export const GIT_COMMIT = "2edb437575d87314cabadc1f6484cadd34c3bf48";
//# sourceMappingURL=version.js.map