// This file is auto-generated by the build system.
export const PACKAGE_NAME = "html-living-framework";
export const PACKAGE_VERSION = "1.0.0";
export const GIT_BRANCH = "main";
export const GIT_COMMIT = "cec68fc694c28842d5aa313117324d4ac7cdff5d";
//# sourceMappingURL=version.js.map