// This file is auto-generated by the build system.
export const PACKAGE_NAME = "html-living-framework";
export const PACKAGE_VERSION = "1.3.0";
export const GIT_BRANCH = "develop";
export const GIT_COMMIT = "e1fdca8929939af740c32187f8cebb8e9ea36015";
//# sourceMappingURL=version.js.map