import { default as EventEmitter } from 'eventemitter3';
import { Bounds, Container, PointerEvents, PointLike } from 'pixi.js';
import { IApplication } from '../../core';
import { Signal } from '../../signals';
import { PointLike as DillPixelPointLike } from '../../utils';
import { IPlugin, Plugin } from '../Plugin';
import { IFocusOutliner, FocusOutliner, FocusOutlinerConfig } from './FocusOutliner';

export type FocusManagerPluginOptions = {
    outliner: IFocusOutliner | Partial<FocusOutlinerConfig> | typeof FocusOutliner;
    usePixiAccessibility: boolean;
};
export interface IFocusable extends EventEmitter {
    isFocused: boolean;
    isKeyDown: boolean;
    focusEnabled: boolean;
    tabIndex: number;
    _accessibleDiv?: HTMLElement;
    accessible: boolean;
    accessibleType: string;
    accessibleTitle: string;
    accessibleHint: string;
    accessiblePointerEvents?: PointerEvents;
    accessibleChildren: boolean;
    onFocusIn: Signal<(focusable: IFocusable) => void>;
    onFocusOut: Signal<(focusable: IFocusable) => void>;
    onFocus: Signal<(focusable: IFocusable) => void>;
    onBlur: Signal<(focusable: IFocusable) => void>;
    position: PointLike;
    focusIn(): void;
    focusOut(): void;
    click(): void;
    blur(): void;
    getGlobalPosition(): PointLike;
    getFocusArea(): Bounds;
    getFocusPosition(): DillPixelPointLike | null;
    getFocusSize(): DillPixelPointLike | null;
}
export interface IFocusLayer {
    currentFocusable: IFocusable | null;
    defaultFocusable: IFocusable | null;
    lastFocusable: IFocusable | null;
    current: boolean;
    availableFocusables: IFocusable[];
    setCurrentFocusable(focusable: IFocusable | null): IFocusable | null;
    hasFocusable(focusable: IFocusable | null): boolean;
    setCurrent(): void;
    addFocusable(focusable: IFocusable, isDefault?: boolean): void;
    removeFocusable(focusable: IFocusable): void;
    sortFocusables(): void;
    next(): IFocusable | null;
    prev(): IFocusable | null;
}
export type FocusChangeDetail = {
    layer: string | number | null;
    focusable: IFocusable | null;
};
export interface IFocusManagerPlugin extends IPlugin {
    readonly view: Container;
    readonly layerCount: number;
    readonly currentLayerId: string | number | null;
    readonly active: boolean;
    readonly layers: Map<string | number, IFocusLayer>;
    onFocusManagerActivated: Signal<() => void>;
    onFocusManagerDeactivated: Signal<() => void>;
    onFocusLayerChange: Signal<(currentLayerId: string | number) => void>;
    onFocusChange: Signal<(detail: FocusChangeDetail) => void>;
    enabled: boolean;
    restart(): void;
    focus(focusable: IFocusable): void;
    forceFocus(focusable: IFocusable): void;
    setFocus(focusable: IFocusable): void;
    addFocusLayer(layerId?: string | number, setAsCurrent?: boolean, focusables?: IFocusable | IFocusable[]): IFocusLayer;
    removeFocusLayer(layerId?: string | number): void;
    setFocusLayer(layerId: string | number): void;
    setLayerOrder(layerIds: (string | number)[]): void;
    add(focusable: IFocusable | IFocusable[], layerId?: string | number, isDefault?: boolean): void;
    addFocusable(focusable: IFocusable | IFocusable[], layerId?: string | number, isDefault?: boolean): void;
    remove(focusable: IFocusable | IFocusable[]): void;
    removeFocusable(focusable: IFocusable | IFocusable[]): void;
    deactivate(): void;
    clearFocus(): void;
    removeAllFocusLayers(): void;
}
export declare class FocusManagerPlugin extends Plugin implements IFocusManagerPlugin {
    readonly id: string;
    readonly view: Container<import('pixi.js').ContainerChild>;
    onFocusManagerActivated: Signal<() => void>;
    onFocusManagerDeactivated: Signal<() => void>;
    onFocusLayerChange: Signal<(currentLayerId: string | number) => void>;
    onFocusChange: Signal<(detail: FocusChangeDetail) => void>;
    private _focusOutliner;
    private _focusTarget;
    private _keyboardActive;
    private _options;
    private _layers;
    get layers(): Map<string | number, IFocusLayer>;
    private _currentLayerId;
    get currentLayerId(): string | number | null;
    private _active;
    get active(): boolean;
    private _enabled;
    get enabled(): boolean;
    set enabled(value: boolean);
    get layerCount(): number;
    initialize(app: IApplication): void;
    destroy(): void;
    deactivate(): void;
    add(focusable: IFocusable | IFocusable[], layerId?: string | number, isDefault?: boolean): void;
    addFocusable(focusable: IFocusable | IFocusable[], layerId?: string | number | null | undefined, isDefault?: boolean): void;
    remove(focusable: IFocusable | IFocusable[]): void;
    removeFocusable(focusable: IFocusable | IFocusable[]): void;
    setLayerOrder(layerIds: (string | number)[]): void;
    addFocusLayer(layerId?: string | number, setAsCurrent?: boolean, focusables?: IFocusable | IFocusable[]): IFocusLayer;
    removeFocusLayer(layerId?: string | number, removeTopLayerIfUndefined?: boolean): void;
    restart(reverse?: boolean): void;
    forceFocus(focusable: IFocusable): void;
    setFocus(focusable: IFocusable): void;
    focus(focusable: IFocusable): void;
    setFocusLayer(layerId: string | number): void;
    postInitialize(_app: IApplication): Promise<void> | void;
    clearFocus(): void;
    removeAllFocusLayers(): void;
    _onKeyDown(e: KeyboardEvent): void;
    _onKeyUp(e: KeyboardEvent): void;
    _onMouseMove(e: MouseEvent): void;
    protected getCoreFunctions(): string[];
    protected getCoreSignals(): string[];
    private _next;
    private _prev;
    private _deactivate;
    private _activate;
    private _updatePixiAccessibility;
    private _getCurrentLayer;
    private _removeTopLayer;
    private _postDelete;
    private _setTarget;
    private _clearFocusTarget;
    private _setupKeyboardListeners;
    private _addGlobalListeners;
    private _removeGlobalListeners;
    private _handleGlobalMouseMove;
    private _handleGlobalPointerDown;
    private _setupAppListeners;
    private _updateOutliner;
}
//# sourceMappingURL=FocusManagerPlugin.d.ts.map