import { IMediaInstance } from '@pixi/sound';
import { Signal } from '../../signals';
import { IAudioChannel } from './AudioChannel';
import { IAudioManager } from './AudioManager';
export interface IAudioInstance {
    volume: number;
    media: IMediaInstance;
    channel: IAudioChannel;
    muted: boolean;
    id: string;
    manager: IAudioManager;
    onStart: Signal<(instance: IAudioInstance) => void>;
    onStop: Signal<(instance: IAudioInstance) => void>;
    onEnd: Signal<(instance: IAudioInstance) => void>;
    onPaused: Signal<(instance: IAudioInstance) => void>;
    onResumed: Signal<(instance: IAudioInstance) => void>;
    isPlaying: boolean;
    fadeTo(volume: number, duration: number): gsap.core.Tween;
    stop(): void;
    destroy(): void;
    remove(): void;
    updateVolume(): void;
    addListeners(): void;
    removeListeners(): void;
    pause(): void;
    play(): void;
    resume(): void;
}
export declare class AudioInstance implements IAudioInstance {
    id: string;
    channel: IAudioChannel;
    manager: IAudioManager;
    onStart: Signal<(instance: IAudioInstance) => void>;
    onStop: Signal<(instance: IAudioInstance) => void>;
    onEnd: Signal<(instance: IAudioInstance) => void>;
    onPaused: Signal<(instance: IAudioInstance) => void>;
    onResumed: Signal<(instance: IAudioInstance) => void>;
    onProgress: Signal<(instance: IAudioInstance) => void>;
    private _media;
    private _volume;
    private _muted;
    private _isPlaying;
    constructor(id: string, channel: IAudioChannel, manager: IAudioManager);
    get media(): IMediaInstance;
    set media(value: IMediaInstance);
    get muted(): boolean;
    set muted(value: boolean);
    get volume(): number;
    set volume(value: number);
    get isPlaying(): boolean;
    pause(): void;
    resume(): void;
    remove(): void;
    stop(): void;
    updateVolume(): void;
    addListeners(): void;
    removeListeners(): void;
    destroy(): void;
    fadeTo(volume: number, duration: number): gsap.core.Tween;
    play(time?: number): void;
    private _handleMediaEnded;
    private _handleMediaStarted;
    private _handleMediaStopped;
    private _handleMediaPaused;
    private _handleMediaProgress;
    private _handleMediaResumed;
}
