export interface ICoreFunctions {
    // FocusManager;
    addFocusable(focusable: IFocusable | IFocusable[], layerId?: string | number | null | undefined, isDefault: boolean = false): void;
    removeFocusable(focusable: IFocusable | IFocusable[]);
    setLayerOrder(layerIds: (string | number)[]): void;
    addFocusLayer(layerId?: string | number, setAsCurrent: boolean = true, focusables?: IFocusable | IFocusable[]): IFocusLayer;
    removeFocusLayer(layerId?: string | number, removeTopLayerIfUndefined = true): void;
    setFocus(focusable: IFocusable);
    setFocusLayer(layerId: string | number): void;
    clearFocus();
    removeAllFocusLayers(): void;
    // i18nModule;
    setLocale(localeId: string);
    t(key: string, params?: i18nTParams, locale: string = this._locale): string;
    // InputManager;
    isControllerActive(controller: InputController): boolean;
    isGamepadActive(gamepad: Gamepad): boolean;
    actions(action: string): ActionSignal<T>;
    sendAction(action: string, data?: T): void;
    setActionContext(context: string | InputContext): void;
    // KeyboardManager;
    onKeyDown(key?: string): KeySignal;
    onKeyUp(key?: string): KeySignal;
    isKeyDown(key: string): boolean;
    // PopupManager;
    addPopup(id: string | number, popup: PopupConstructor<T>): void;
    showPopup(id: string | number, config: Partial<PopupConfig<T>> = {}): Promise<IPopup<T> | undefined>;
    hidePopup(id: string | number, data?: T): Promise<IPopup<T> | undefined>;
    removeAllPopups(animate: boolean = false): void;
    // SceneManager;
    loadScene(sceneIdOrLoadSceneConfig: LoadSceneConfig | string): Promise<void>;
}
