import {
  Application,
  BitmapText,
  Container,
  DisplayObject,
  Graphics,
  HTMLText,
  HTMLTextStyle,
  Point,
  Rectangle,
  Sprite,
  Text,
  TextStyle,
  Texture,
} from 'pixi.js';

const PIXI = {
  Application,
  DisplayObject,
  Container,
  Sprite,
  Graphics,
  Text,
  BitmapText,
  HTMLText,
  Texture,
  Point,
  Rectangle,
  TextStyle,
  HTMLTextStyle,
};

export { PIXI };

export type {
  Application as PIXIApplication,
  DisplayObject as PIXIDisplayObject,
  Container as PIXIContainer,
  Sprite as PIXISprite,
  Graphics as PIXIGraphics,
  Text as PIXIText,
  BitmapText as PIXIBitmapText,
  HTMLText as PIXIHTMLText,
  Texture as PIXITexture,
  Point as PIXIPoint,
  Rectangle as PIXIRectangle,
  TextStyle as PIXITextStyle,
  HTMLTextStyle as PIXIHTMLTextStyle,
  IApplicationOptions,
  IPoint,
  IHitArea,
  ITextStyle,
  IHTMLTextStyle,
  IBitmapTextStyle,
} from 'pixi.js';
