// This file is auto-generated by the build system.
export const PACKAGE_NAME: string = "html-living-framework";
export const PACKAGE_VERSION: string = "1.6.0";
export const GIT_BRANCH: string | undefined = "main";
export const GIT_COMMIT: string | undefined = "f418e6faf701484c4be05e98febdb3dd6977edbb";
