// This file is auto-generated by the build system.
export const PACKAGE_NAME: string = "html-living-framework";
export const PACKAGE_VERSION: string = "1.6.1";
export const GIT_BRANCH: string | undefined = "main";
export const GIT_COMMIT: string | undefined = "2edb437575d87314cabadc1f6484cadd34c3bf48";
