// This file is auto-generated by the build system.
export const PACKAGE_NAME: string = "html-living-framework";
export const PACKAGE_VERSION: string = "1.6.0";
export const GIT_BRANCH: string | undefined = "develop";
export const GIT_COMMIT: string | undefined = "33a177963738995be9181aea5e37c73e866c5b7b";
