import { Container } from 'pixi.js';
import { PIXIContainer } from '../../../pixi';
import { Signal } from '../../../signals';
import { Actor } from './Actor';
import { Entity } from './Entity';
import { Sensor } from './Sensor';
import { Solid } from './Solid';
import { SpatialHashGrid } from './SpatialHashGrid';
import { Collision, EntityType, Side, SpatialHashGridFilter } from './types';
import { Wall } from './Wall';
export declare class System {
    private static gfx;
    private static _collisionResolver;
    static container: Container<any>;
    static grid: SpatialHashGrid;
    static fps: number;
    static debug: boolean;
    static typeMap: Map<EntityType, Entity[]>;
    static actors: Actor[];
    static solids: Solid[];
    static sensors: Sensor[];
    static enabled: boolean;
    static gravity: number;
    static onCollision: Signal<(collision: Collision) => void>;
    static worldBounds: Wall[];
    static useSpatialHashGrid(cellSize: number): void;
    static resolveCollision(collision: Collision): boolean;
    static addEntity(entity: Entity): void;
    static removeEntity(entity: Entity): void;
    static getEntitiesByType<T extends Entity = Entity>(...type: EntityType[]): T[];
    static addActor(actor: Actor): void;
    static addSolid(solid: Solid): void;
    static addSensor(sensor: Sensor): void;
    static removeActor(actor: Actor): void;
    static removeSolid(solid: Solid): void;
    static removeSensor(sensor: Sensor): void;
    static getNearbyEntities(entity: Entity, onlyTypes?: string[]): Entity[];
    static getNearbyEntities(entity: Entity, filter?: SpatialHashGridFilter): Entity[];
    static update(deltaTime: number): void;
    static addBoundary(width: number, height: number, size?: number, padding?: number, sides?: Side[]): void;
    static collide(collision: Collision): void;
    static drawDebug(): void;
    static setContainer(container: PIXIContainer): void;
    static initialize(opts: Partial<TowerFallPhysicsSystemOptions>): void;
    static updateEntity(entity: Entity): void;
    static get all(): Entity[];
    static get totalEntities(): number;
    static set collisionResolver(collisionResolverMethod: (collision: Collision) => boolean);
}
type TowerFallPhysicsBoundaryOptions = {
    width: number;
    height: number;
    thickness: number;
    padding: number;
    sides: Side[];
};
type OptionalTowerFallPhysicsBoundaryOptions = Partial<TowerFallPhysicsBoundaryOptions>;
type RequiredWidthAndHeight = Required<Pick<TowerFallPhysicsBoundaryOptions, 'width' | 'height'>>;
type CustomTowerFallPhysicsBoundaryOptions = OptionalTowerFallPhysicsBoundaryOptions & RequiredWidthAndHeight;
type TowerFallPhysicsSystemOptions = {
    gravity: number;
    container: PIXIContainer;
    debug: boolean;
    boundary: CustomTowerFallPhysicsBoundaryOptions;
    collisionResolver: (collision: Collision) => boolean;
};
export {};
