name: Deploy Docs

on:
  pull_request:
    types: [ closed ]
    paths:
      - '**.json'
      - '**.yaml'
      - '**.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: (github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'release')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Build Docs
        run: npm run docs

      - name: Deploy to Remote Host via SFTP
        uses: ticoraap/sftp-mirror@v1.6
        with:
          server: ${{ secrets.DOCS_SFTP_HOST }}
          user: ${{ secrets.DOCS_SFTP_USERNAME }}
          password: ${{ secrets.DOCS_SFTP_PASSWORD }}
          port: ${{ secrets.DOCS_SFTP_PORT }}
          local: './docs/dist/'
          remote: '/docs/'
