name: Deploy TS Docs to hlf.reli.sh/docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Build Docs
        run: npm run docs

      - name: Deploy to Remote Host via SFTP
        uses: JamsRepos/SFTP-Deploy-Action@v2.1
        with:
          server: ${{ secrets.DOCS_SFTP_HOST }}
          username: ${{ secrets.DOCS_SFTP_USERNAME }}
          ssh_password: ${{ secrets.DOCS_SFTP_PASSWORD }}
          port: ${{ secrets.DOCS_SFTP_PORT }}
          local_path: './docs/*'
          remote_path: '/docs'
          args: '-o ConnectTimeout=5'
