name: Publish Package to NPM
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Send Google chat notification
        env:
          WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

        run: |
          TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
          curl -X POST -H 'Content-Type: application/json' $WEBHOOK_URL -d "{
              \"text\": \"A new Dill Pixel release just dropped! Check it out here: https://github.com/relishinc/dill-pixel/releases/tag/$TAG_NAME\"
          }"
