name: Release Notifications

on:
  pull_request:
    types: [ closed ]
    paths:
      - '**.json'
      - '**.yaml'
      - '**.yml'
    branches:
      - main

jobs:
  notify:
    if:
      github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'chore(main): release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Send Google chat notification
        env:
          WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        run: |
          TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
          curl -X POST -H 'Content-Type: application/json' $WEBHOOK_URL -d "{
              \"text\": \"A new release was just added: $TAG_NAME\"
          }"
