name: Update Version File

# Trigger this action when a pull request is merged to main
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'release')
    steps:
      - name: Delay
        run: sleep 10

      # Step to checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Fetch all git tags and branches
      - run: git fetch --prune --unshallow

      # Step to create version.ts file based on package.json version and git information
      - name: Create Version File
        run: |
          PACKAGE_VERSION=$(jq -r ".version" package.json)
          GIT_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
          GIT_COMMIT=$(git rev-parse HEAD)

          echo "export const PACKAGE_NAME: string = \"html-living-framework\";" > ./src/version.ts
          echo "export const PACKAGE_VERSION: string = \"$PACKAGE_VERSION\";" >> ./src/version.ts
          echo "export const GIT_BRANCH: string = \"$GIT_BRANCH\";" >> ./src/version.ts
          echo "export const GIT_COMMIT: string = \"$GIT_COMMIT\";" >> ./src/version.ts

      # Step to commit and push the version.ts file
      - name: Commit and push version file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./src/version.ts
          git commit -m "Update version.ts file"
          git push
